# Generated by Django 3.2.12 on 2022-09-14 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alpha', '0002_remove_land_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='land',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
