# Generated by Django 3.2.12 on 2022-09-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0007_auto_20220921_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hook_text',
        ),
    ]
